<a href="https://colab.research.google.com/github/advaynalla/colab/blob/main/PandasAndPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Data Preprocessing




In [ ]:
#dataset from here: https://www.kaggle.com/c/titanic/data

In [ ]:
# 2. Pandas DataFrames
import pandas as pd

df = pd.read_csv("train.csv")  # Replace with real CSV
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df["Embarked"].unique()


array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
df["Embarked"] = df["Embarked"].fillna(0)

In [ ]:

df["Embarked"] = df["Embarked"].map({0:0,"S": 1, "C": 2, "Q": 3})
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN         1  
1        0          PC 17599  71.2833   C85         2  
2        0  STON/O2. 3101282   7.9250   NaN         1  
3        0            113803  53.1000  C123         1  
4        0            373450   8.0500   NaN         1  
..     ...               ...      ...   ...       ...  
886      0            211536  13.0000   NaN         1  
887      0            112053  30.0000   B42         1  
888      2        W./C. 6607  23.4500   NaN         1  
889      0            111369  30.0000  C148         2  
890      0            370376   7.7500   NaN         3  

[891 rows x 12 columns]

In [ ]:
df["Sex"].unique()


array(['male', 'female'], dtype=object)

In [ ]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN         1  
1        0          PC 17599  71.2833   C85         2  
2        0  STON/O2. 3101282   7.9250   NaN         1  
3        0            113803  53.1000  C123         1  
4        0            373450   8.0500   NaN         1  
..     ...               ...      ...   ...       ...  
886      0            211536  13.0000   NaN         1  
887      0            112053  30.0000   B42         1  
888      2        W./C. 6607  23.4500   NaN         1  
889      0            111369  30.0000  C148         2  
890      0            370376   7.7500   NaN         3  

[891 rows x 12 columns]

In [ ]:
df["Survived"].unique()

array([0, 1])

In [ ]:
df["Age"].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
df["Age"].fillna(df["Age"].mean(), inplace=True)
df

<ipython-input-34-25627f81ba38>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.000000      1   
2                               Heikkinen, Miss. Laina    1  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.000000      1   
4                             Allen, Mr. William Henry    0  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    0  27.000000      0   
887                       Graham, Miss. Margaret Edith    1  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1  29.699118      1   
889                              Behr, Mr. Karl Howell    0  26.000000      0   
890                                Dooley, Mr. Patrick    0  32.000000      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN         1  
1        0          PC 17599  71.2833   C85         2  
2        0  STON/O2. 3101282   7.9250   NaN         1  
3        0            113803  53.1000  C123         1  
4        0            373450   8.0500   NaN         1  
..     ...               ...      ...   ...       ...  
886      0            211536  13.0000   NaN         1  
887      0            112053  30.0000   B42         1  
888      2        W./C. 6607  23.4500   NaN         1  
889      0            111369  30.0000  C148         2  
890      0            370376   7.7500   NaN         3  

[891 rows x 12 columns]

In [ ]:
df["Pclass"].unique()

array([3, 1, 2])

In [ ]:
df["SibSp"].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [ ]:
df["Parch"].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [ ]:
df["Fare"].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [ ]:
# 3. Scikit-learn: Model Training
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Example columns: adjust for your CSV
X = df[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]
y = df["Survived"]

#y = mx + b


In [ ]:
X

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    0  22.000000      1      0   7.2500         1
1         1    1  38.000000      1      0  71.2833         2
2         3    1  26.000000      0      0   7.9250         1
3         1    1  35.000000      1      0  53.1000         1
4         3    0  35.000000      0      0   8.0500         1
..      ...  ...        ...    ...    ...      ...       ...
886       2    0  27.000000      0      0  13.0000         1
887       1    1  19.000000      0      0  30.0000         1
888       3    1  29.699118      1      2  23.4500         1
889       1    0  26.000000      0      0  30.0000         2
890       3    0  32.000000      0      0   7.7500         3

[891 rows x 7 columns]

In [ ]:
embarked_one_hot = pd.get_dummies(X['Embarked'], prefix='Embarked')

# Add the new one-hot columns and drop the original 'Embarked' column
X = pd.concat([X.drop('Embarked', axis=1), embarked_one_hot], axis=1)

In [ ]:
X[['Embarked_0', 'Embarked_1', 'Embarked_2', 'Embarked_3']] = X[['Embarked_0', 'Embarked_1', 'Embarked_2', 'Embarked_3']].astype(int)


In [ ]:
X

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked_0  Embarked_1  \
0         3    0  22.000000      1      0   7.2500           0           1   
1         1    1  38.000000      1      0  71.2833           0           0   
2         3    1  26.000000      0      0   7.9250           0           1   
3         1    1  35.000000      1      0  53.1000           0           1   
4         3    0  35.000000      0      0   8.0500           0           1   
..      ...  ...        ...    ...    ...      ...         ...         ...   
886       2    0  27.000000      0      0  13.0000           0           1   
887       1    1  19.000000      0      0  30.0000           0           1   
888       3    1  29.699118      1      2  23.4500           0           1   
889       1    0  26.000000      0      0  30.0000           0           0   
890       3    0  32.000000      0      0   7.7500           0           0   

     Embarked_2  Embarked_3  
0             0           0  
1             1           0  
2             0           0  
3             0           0  
4             0           0  
..          ...         ...  
886           0           0  
887           0           0  
888           0           0  
889           1           0  
890           0           1  

[891 rows x 10 columns]

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# pytorch tensors

In [ ]:
import torch

# Scalars (0D Tensor)
a = torch.tensor(5)
print("Scalar (0D):", a)
print("Shape:", a.shape)


Scalar (0D): tensor(5)
Shape: torch.Size([])


In [ ]:
# Vectors (1D Tensor)
b = torch.tensor([1, 2, 3])
print("\nVector (1D):", b)
print("Shape:", b.shape)




Vector (1D): tensor([1, 2, 3])
Shape: torch.Size([3])


In [ ]:
# Matrices (2D Tensor)
c = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("\nMatrix (2D):\n", c)
print("Shape:", c.shape)




Matrix (2D):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [ ]:
# 3D Tensors (think of stacking matrices)
d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D Tensor:\n", d)
print("Shape:", d.shape)


3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20, 30])

# Element-wise Addition
add_result = x + 5
print("Addition:", add_result)

# Element-wise Multiplication
mult_result = y * 5
print("Multiplication:", mult_result)

Addition: tensor([6, 7, 8])
Multiplication: tensor([ 50, 100, 150])


In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20, 30])

# Element-wise Addition
add_result = x + y
print("Addition:", add_result)

# Element-wise Multiplication
mult_result = x * y
print("Multiplication:", mult_result)


Addition: tensor([11, 22, 33])
Multiplication: tensor([10, 40, 90])


# back to training neural network

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X_train

Pclass  Sex        Age  SibSp  Parch      Fare  Embarked_0  Embarked_1  \
331       1    0  45.500000      0      0   28.5000           0           1   
733       2    0  23.000000      0      0   13.0000           0           1   
382       3    0  32.000000      0      0    7.9250           0           1   
704       3    0  26.000000      1      0    7.8542           0           1   
813       3    1   6.000000      4      2   31.2750           0           1   
..      ...  ...        ...    ...    ...       ...         ...         ...   
106       3    1  21.000000      0      0    7.6500           0           1   
270       1    0  29.699118      0      0   31.0000           0           1   
860       3    0  41.000000      2      0   14.1083           0           1   
435       1    1  14.000000      1      2  120.0000           0           1   
102       1    0  21.000000      0      1   77.2875           0           1   

     Embarked_2  Embarked_3  
331           0           0  
733           0           0  
382           0           0  
704           0           0  
813           0           0  
..          ...         ...  
106           0           0  
270           0           0  
860           0           0  
435           0           0  
102           0           0  

[712 rows x 10 columns]

In [ ]:
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values.flatten(), dtype=torch.float32)

X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values.flatten(), dtype=torch.float32)

In [ ]:
X_train_tensor

tensor([[ 1.0000,  0.0000, 45.5000,  ...,  1.0000,  0.0000,  0.0000],
        [ 2.0000,  0.0000, 23.0000,  ...,  1.0000,  0.0000,  0.0000],
        [ 3.0000,  0.0000, 32.0000,  ...,  1.0000,  0.0000,  0.0000],
        ...,
        [ 3.0000,  0.0000, 41.0000,  ...,  1.0000,  0.0000,  0.0000],
        [ 1.0000,  1.0000, 14.0000,  ...,  1.0000,  0.0000,  0.0000],
        [ 1.0000,  0.0000, 21.0000,  ...,  1.0000,  0.0000,  0.0000]])

In [ ]:
X_train_tensor.shape

torch.Size([712, 10])

In [ ]:
y_train_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
        0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
        1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
        1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 

In [ ]:
y_train_tensor.shape

torch.Size([712])

In [ ]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [ ]:
sample_X, sample_y = train_dataset[5]
print("First Sample Features (X):", sample_X)
print("First Sample Label (y):", sample_y)

First Sample Features (X): tensor([  1.0000,   0.0000,  24.0000,   0.0000,   1.0000, 247.5208,   0.0000,
          0.0000,   1.0000,   0.0000])
First Sample Label (y): tensor(0.)


In [ ]:

batch_size = 1

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [ ]:
for batch_X, batch_y in train_loader:
    print("Batch Features (X):\n", batch_X)
    print("Batch Labels (y):\n", batch_y)
    print("\n")

Batch Features (X):
 tensor([[ 1.0000,  0.0000, 65.0000,  0.0000,  0.0000, 26.5500,  0.0000,  1.0000,
          0.0000,  0.0000]])
Batch Labels (y):
 tensor([0.])


Batch Features (X):
 tensor([[ 3.0000,  1.0000, 29.6991,  2.0000,  0.0000, 23.2500,  0.0000,  0.0000,
          0.0000,  1.0000]])
Batch Labels (y):
 tensor([1.])


Batch Features (X):
 tensor([[ 3.0000,  0.0000, 26.0000,  0.0000,  0.0000,  7.8958,  0.0000,  1.0000,
          0.0000,  0.0000]])
Batch Labels (y):
 tensor([0.])


Batch Features (X):
 tensor([[ 2.0000,  1.0000,  5.0000,  1.0000,  2.0000, 27.7500,  0.0000,  1.0000,
          0.0000,  0.0000]])
Batch Labels (y):
 tensor([1.])


Batch Features (X):
 tensor([[  1.0000,   1.0000,  58.0000,   0.0000,   0.0000, 146.5208,   0.0000,
           0.0000,   1.0000,   0.0000]])
Batch Labels (y):
 tensor([1.])


Batch Features (X):
 tensor([[ 3.0000,  0.0000, 29.0000,  0.0000,  0.0000,  7.8958,  0.0000,  0.0000,
          1.0000,  0.0000]])
Batch Labels (y):
 tensor([1.])




In [ ]:
import torch.nn as nn

class SimpleNet(nn.Module):                     #always
    def __init__(self):                         #always
        super(SimpleNet, self).__init__()       #always


        self.fc1 = nn.Linear(10, 16)
        self.fc2 = nn.Linear(16, 8)
        self.fc3 = nn.Linear(8, 1)

    def forward(self, x):                       #always


        x = self.fc1(x)
        x = nn.functional.relu(x)

        x = self.fc2(x)
        x = nn.functional.relu(x)

        x = self.fc3(x)
        x = torch.sigmoid(x)


        return x

model = SimpleNet()

In [ ]:
x, y = train_dataset[0]
output = model(x)
output

tensor([0.9136], grad_fn=<SigmoidBackward0>)

In [ ]:
import torch.optim as optim

criterion = nn.BCELoss()  # Binary Cross-Entropy Loss since we're doing binary classification

optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam is a good default choice

In [ ]:
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor).squeeze()
    test_preds = (test_outputs >= 0.5).float()
    test_accuracy = (test_preds == y_test_tensor).sum().item() / len(y_test_tensor)

print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Test Accuracy: {test_accuracy * 100:.2f}%")


Epoch [1/100], Loss: 0.4817, Test Accuracy: 39.11%


In [ ]:
epochs = 100

for epoch in range(epochs):
    model.train()
    for batch_X, batch_y in train_loader:
        outputs = model(batch_X).squeeze()
        #print(outputs, batch_y.squeeze())
        loss = criterion(outputs, batch_y.squeeze())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Evaluate on test data
    model.eval()
    with torch.no_grad():
        test_outputs = model(X_test_tensor).squeeze()
        test_preds = (test_outputs >= 0.5).float()
        test_accuracy = (test_preds == y_test_tensor).sum().item() / len(y_test_tensor)

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Test Accuracy: {test_accuracy * 100:.2f}%")


Epoch [1/100], Loss: 0.1462, Test Accuracy: 68.72%
Epoch [2/100], Loss: 0.5120, Test Accuracy: 78.77%
Epoch [3/100], Loss: 0.1881, Test Accuracy: 79.89%
Epoch [4/100], Loss: 0.6789, Test Accuracy: 80.45%
Epoch [5/100], Loss: 1.5280, Test Accuracy: 79.89%
Epoch [6/100], Loss: 0.1412, Test Accuracy: 81.56%
Epoch [7/100], Loss: 0.3294, Test Accuracy: 78.21%
Epoch [8/100], Loss: 0.1505, Test Accuracy: 81.01%
Epoch [9/100], Loss: 0.1195, Test Accuracy: 79.89%
Epoch [10/100], Loss: 0.0861, Test Accuracy: 79.89%
Epoch [11/100], Loss: 0.7805, Test Accuracy: 77.65%
Epoch [12/100], Loss: 0.7227, Test Accuracy: 81.56%
Epoch [13/100], Loss: 0.2466, Test Accuracy: 79.33%
Epoch [14/100], Loss: 0.3950, Test Accuracy: 79.33%
Epoch [15/100], Loss: 0.0608, Test Accuracy: 82.12%
Epoch [16/100], Loss: 2.4429, Test Accuracy: 78.77%
Epoch [17/100], Loss: 0.1397, Test Accuracy: 79.33%
Epoch [18/100], Loss: 0.1314, Test Accuracy: 81.56%
Epoch [19/100], Loss: 0.1964, Test Accuracy: 81.56%
Epoch [20/100], Loss:

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Epoch [79/100], Loss: 0.8309, Test Accuracy: 79.33%
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-95-6adf7f79bb41>", line 12, in <cell line: 0>
    optimizer.step()
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 493, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 91, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line 234, in step
    has_complex = self._init_group(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line None, in _init_group
KeyboardInterrupt

During handling of the above exception, another excepti

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-95-6adf7f79bb41>", line 12, in <cell line: 0>
    optimizer.step()
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 493, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 91, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line 234, in step
    has_complex = self._init_group(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line None, in _init_group
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  F